# Generated by Django 4.2.30 on 2026-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpticalServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_tier', models.CharField(default='standard', max_length=50)),
                ('project_title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('beamer_data_prep', 'BEAMER - E-Beam Data Prep & Proximity Effect Correction'), ('lab_3d_litho', 'LAB - 3D Optical & E-Beam Lithography Simulation'), ('tracer_monte_carlo', 'TRACER - Monte Carlo PSF & Energy Deposition Calculation'), ('prosem_metrology', 'ProSEM - SEM Image Analysis & CD Metrology'), ('beamer_3d_greyscale', 'BEAMER 3D - Greyscale Lithography Surface Profiling')], default='beamer_data_prep', max_length=100)),
                ('industry', models.CharField(default='semiconductor', max_length=100)),
                ('wavelength_range', models.CharField(default='100 kV Acceleration Voltage', max_length=100)),
                ('analysis_tools', models.CharField(default='PMMA Positive Resist, 300mm Silicon Wafer', max_length=255)),
                ('system_specifications', models.TextField(blank=True, null=True)),
                ('cad_file_attached', models.CharField(default='GDSII Layout Provided', max_length=255)),
                ('status', models.CharField(default='Pending Analysis', max_length=50)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(default='E-Beam & Lithography Simulation', max_length=100)),
                ('version', models.CharField(default='2026.1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('software_choice', models.CharField(default='BEAMER - E-Beam Lithography Data Prep', max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('plan_tier', models.CharField(choices=[('basic', 'Academic Litho License ($149/mo)'), ('standard', 'Commercial Fab Suite ($499/mo)'), ('premium', 'Enterprise Litho Foundry ($999/mo)')], default='standard', max_length=20)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
